from distutils.core import setup

setup(name='coinunifier',
      version='0.2.2',
      author='WalletMona.com',
      author_email='walletmona@gmail.com',
      url='http://github.com/walletmona/coinunifier/',
      description='Easy unification of divisional coins based on Bitcoin protocol.',
      packages=['coinunifier', 'coinunifier.wallet'],
      keywords='cryptocurrency bitcoin litecoin coins wallet',
      license='GNU GPL v2',
      classifiers=['Development Status :: 3 - Alpha',
                   'Environment :: Console',
                   'Intended Audience :: Developers',
                   'Intended Audience :: End Users/Desktop',
                   'License :: OSI Approved :: GNU General Public License v2 (GPLv2)',
                   'Natural Language :: English',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python :: 2 :: Only',
                   'Topic :: Other/Nonlisted Topic',
                   'Topic :: Utilities',
                  ],
      scripts = ['script/send_coins.py', 'script/unify_coins_simple.py'],
      requires = ['bitcoinrpc'],
     )
